<?php

function crag_entity_info() {
    $crag_info['crag'] = array(
        'label' => 'Crag name',
        'controller class' => 'CragController',
        'base table' => 'crags',
		'label callback' => 'crag_label',
        'uri callback' => 'crag_uri',
        'fieldable' => true,
        'entity keys' => array(
            'id' => 'cid',
            'name' => 'name',
        ),
        'static cache' => true,
        'bundles' => array(
            'crag' => array(
                'label' => 'Crag Name',
                'admin' => array(
                    'path' => 'admin/structure/crag/manage',
                    'access arguments' => array('administer crags'),
                ),
            ),
        ),
        'view modes' => array(
            'full' => array(
                'label' => 'Crags',
                'custom settings' => false,
            ),
        )
    );
    
    return $crag_info;
}

function crag_uri($crag) {
    return array(
        'path' => 'crag/' . $crag->id
    );
}

function crag_label($crags) {
    return $crags->name;
}

function crag_load($cid = null, $reset = false) {
    $cids = (isset ($cid) ? array($cid) : array());
    $crag = crag_load_multiple($cids, $reset);
    return $crag ? reset($crag) : false;
}

function crag_load_multiple($cids = array(), $conditions = array(), $reset = false) {
    return entity_load('crag', $cids, $conditions, $reset);
}

function crag_save($crag) {
    return entity_get_controller('crag')->save($crag);
}

function crag_permission() {
    return array(
        'administer crags' => array(
            'title' => 'Administer crags',
            'restrict access' => true,
        ),
        'view crags' => array(
            'title' => 'View crags'
        ),
        'create crag' => array(
            'title' => 'Create crags'
        )
    );
}

function crag_menu() {
    $items['admin/structure/crag/manage'] = array(
        'title' => 'Crag admin',
        'description' => 'Manage crag structure',
        'page callback' => 'crag_info',
        'access arguments' => array('administer crags'),
    );
    
    $items['crag/%crag'] = array(
        'title callback' => 'crag_page_title',
        'title arguments' => array(1),
        'page callback' => 'crag_page_view',
        'page arguments' => array(1),
        'access arguments' => array('view crags'),
        'type' => MENU_CALLBACK
    );
    
    $items['crag/add'] = array(
        'title' => 'Add crag',
        'page callback' => 'crag_add',
        'access arguments' => array('create crag')
    );
    
    $items['crag/%crag/edit'] = array(
        'title callback' => 'crag_page_title',
        'title arguments' => array(1),
        'page callback' => 'crag_edit',
        'page arguments' => array(1),
        'access arguments' => array('view crags'),
        'type' => MENU_CALLBACK
    );
    
    
    return $items;
}

function crag_info() {
    return 'Welcome to the administration page for your crags!';
}

function crag_page_title($crag) {
    return $crag->name;
}

function crag_page_view($crag, $view_mode = 'full') {
    $crag->content = array();
    
    // Build fields content
    field_attach_prepare_view('crag', array($crag->cid => $crag), $view_mode);
    entity_prepare_view('crag', array($crag->cid => $crag));
    $crag->content += field_attach_view('crag', $crag, $view_mode);
    
    return $crag->content;
}

function crag_edit($crag){
  return drupal_get_form('crag_add_form', $crag);
}

function crag_field_extra_fields() {
    $return = array();
    $return['crag']['crag'] = array(
        'form' => array(
            'name' => array(
                'label' => 'Name',
                'description' => 'crag name',
				'weight' => 0,
   	       ),
		
            'ne_bounds_lat' => array(
                'label' => 'Northeast bounds latitude',
                'description' => 'northeast bounds latitude',
				'weight' => 20,
			),
		
            'ne_bounds_lon' => array(
                'label' => 'Northeast bounds longitude',
                'description' => 'northeast bounds longitude',
				'weight' => 21,
			),
		
            'sw_bounds_lat' => array(
                'label' => 'Southwest bounds latitude',
                'description' => 'southwest bounds latitude',
				'weight' => 22,
     	   ),
		
            'sw_bounds_lon' => array(
                'label' => 'Southwest bounds longitude',
                'description' => 'southwest bounds longitude',
				'weight' => 23,
			),
		),
    );
    
    return $return;
}

function crag_add() {
    $crag = (object) array(
        'cid' => '',
        'type' => 'crag',
        'name' => ''
    );
    
    return drupal_get_form('crag_add_form', $crag);
}


function crag_add_form($form, $form_state, $crag) {
	drupal_add_js('http://maps.google.com/maps/api/js?sensor=true',array('type' => 'external','weight' => -200));
	$form['name'] = array(
        '#type' => 'textfield',
        '#title' => 'Name',
        '#default_value' => isset($crag->name) ? $crag->name : '',
        '#required' => true,
		'#weight' => 0
    );
 // $form['mapbox'] = array(
 //   '#type' => 'markup',
 //   '#title' =>"Drag the marker to place your area.",
 //   '#value' => 'Here is my markup',
 //   '#prefix' => '<iframe src="http://www.thannmap.appspot.com" style="width:1000px;height:500px"></iframe>',
 //   '#suffix' => '</br>',
 // );
  
	$form['ne_bounds_lat'] = array(
        '#type' => 'textfield',
        '#title' => t('Northeast bounds latitude'),
        '#default_value' => isset($crag->ne_bounds_lat) ? $crag->ne_bounds_lat : '',
        '#size' => 16,
        '#maxlength' => 20,
        
    );
	
	 $form['ne_bounds_lon'] = array(
        '#type' => 'textfield',
        '#title' => t('Northeast bounds longitude'),
        '#default_value' => isset($crag->ne_bounds_lon) ? $crag->ne_bounds_lon : '',
        '#size' => 16,
        '#maxlength' => 20,
        
    );	
	
	 $form['sw_bounds_lat'] = array(
        '#type' => 'textfield',
        '#title' => t('Southwest bounds latitude'),
        '#default_value' => isset($crag->sw_bounds_lat) ? $crag->sw_bounds_lat : '',
        '#size' => 16,
        '#maxlength' => 20,
        
    );	
	
	$form['sw_bounds_lon'] = array(
        '#type' => 'textfield',
        '#title' => t('Southwest bounds longitude'),
        '#default_value' => isset($crag->sw_bounds_lon) ? $crag->sw_bounds_lon : '',
        '#size' => 16,
        '#maxlength' => 20,
        
    );
		
    $form['actions'] = array(
        '#type' => 'actions'
    );
    
    $form['actions']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Save')
    );
    
    field_attach_form('crag', $crag, $form, $form_state);
    
    return $form;
}

function crag_add_form_validate($form, $form_state) {
    $crag_submission = (object)$form_state['values'];
    field_attach_form_validate('crag', $crag_submission, $form, $form_state);
}

function crag_add_form_submit($form, $form_state) {
    $crag_submission = (object) $form_state['values'];
    field_attach_submit('crag', $crag_submission, $form, $form_state);
    $crag = crag_save($crag_submission);
    $form_state['redirect'] = "crag/$crag->cid";
}
function crag_form_alter($form, $form_state, $form_id)  {
      switch ($form_id)  {
  	 	case 'crag_add_form':
  	 		$form['ne_bounds_lat']['#default_value'] = isset($_GET["NElat"]) ? htmlspecialchars($_GET["NElat"]) : '';
			$form['ne_bounds_lon']['#default_value'] = isset($_GET["NElng"]) ? htmlspecialchars($_GET["NElng"]) : '';
  	 		$form['sw_bounds_lat']['#default_value'] = isset($_GET["SWlat"]) ? htmlspecialchars($_GET["SWlat"]) : '';
			$form['sw_bounds_lon']['#default_value'] = isset($_GET["SWlng"]) ? htmlspecialchars($_GET["SWlng"]) : '';
			$form['field_crag_parent_area']['und']['#default_value'] = isset($_GET["parent"]) ?htmlspecialchars($_GET["parent"]) : '';
        // print_r($form['field_crag_parent_area']['und']);

  	 		break;
  	 }
  }
